apiVersion: apps/v1
kind: Deployment 
metadata:
  name: usermgmt-microservice
  labels:
    app: usermgmt-restapp
spec: #here spec has 3 core child elements 1.replicas 2.container 3.template
  replicas: 1
  selector:
    matchLabels:
      app: usermgmt-restapp #e name same as template section lo labels app name
  template:  #template is nothing but pod template define po in this section,  child elements are metada and spec
    metadata:
      labels: 
        app: usermgmt-restapp #selector mathchlabels lo vunna name ea ekakda evvali
    spec:
      containers:
        - name: usermgmt-restapp
          image: stacksimplify/kube-usermanagement-microservice:1.0.0
          ports: 
            - containerPort: 8095           
          env:
            - name: DB_HOSTNAME
              value: "mysql"            
            - name: DB_PORT
              value: "3306"            
            - name: DB_NAME
              value: "usermgmt"            
            - name: DB_USERNAME
              value: "root"            
            - name: DB_PASSWORD
              value: "dbpassword11"            


