apiVersion: v1
kind: Service
metadata:
  name: usermgmt-restapp-service
  labels: 
    app: usermgmt-restapp #send the request as per the pod/cpntainer name
spec:
  type: NodePort
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 8095
      targetPort: 8095
      nodePort: 31231

# ebs volumes tho problem enti antey app create ipothundi kain mysql run avvatledhui
#our applicatione should not start before the mysql starts, we resolve this issue with AWS RDS
#by using init containers can start mysql cont first then start app container
