apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-mysql-pv-claim
spec: 
  accessModes:
    - ReadWriteOnce
  storageClassName: ebs-sc #this is the line to get the storage class and same name as metadata section
  resources: 
    requests:
      storage: 4Gi