apiVersion: v1
kind: Service
metadata:
  name: myapp-pod-nodeport-service #name of the service
spec:
  type: NodePort 
  selector:
    app: myapp  #description below
  ports: 
    - name: http
      port: 80 # Service Port
      targetPort: 80 # Container Port
      nodePort: 31231 # NodePort

#manam service file lo eadaite "selector app" lo echamo adhi manam pod loni "labels app" section nundi techukunnam
#edhi enduku antey service create chesinappudu ah service based on the selector lo vunna name ki traffic provide chestadi
#ah "selectorapp" lo vunna name and pod file lo vunna "labels app" tho match cheskoni equal itey ah particular pod ki traffic provide chestadi.