apiVersion: v1
kind: Service
metadata:
  name: replicaset-nodeport-service
spec:
  type: NodePort 
  selector: 
    app: myapp2 
  ports: 
    - name: http
      port: 80
      targetPort: 80
      nodePort: 31232

#ekkada "selector" lo vunna value ni "labels" nundi techukuntam replicaset create chesinappudu
    